# **DESCRIPTIVE ANALYSIS OF OUR DATA**

In [9]:
import pandas as pd
import numpy as np
# Load dataset
DATA_PATH = 'data.csv'

df = pd.read_csv(DATA_PATH)
rows, cols = df.shape
print(f'The dataset contains {rows} rows and {cols} columns.')
df.head(10)

The dataset contains 476 rows and 17 columns.

,id,text,relations,diagnosis,solutions,id_1,label_1,start_offset_1,end_offset_1,id_2,label_2,start_offset_2,end_offset_2,id_3,label_3,start_offset_3,end_offset_3
0,249,A cybersquatting domain save-russia[.]today is...,"[{'from_id': 44658, 'id': 9, 'to_id': 44659, '...",The diagnosis is a cyber attack that involves ...,1. Implementing DNS filtering to block access ...,44656,attack-pattern,2,16,44657,url,24,43,44658.0,attack-pattern,57.0,68.0
1,14309,"Like the Android Maikspy, it first sends a not...","[{'from_id': 48531, 'id': 445, 'to_id': 48532,...",The diagnosis is that the entity identified as...,1. Implementing a robust anti-malware software...,48530,SOFTWARE,9,17,48531,malware,17,24,48532.0,Infrastucture,63.0,73.0
2,13996,While analyzing the technical details of this ...,"[{'from_id': 48781, 'id': 461, 'to_id': 48782,...",Diagnosis: APT37/Reaper/Group 123 is responsib...,1. Implementing advanced threat detection tech...,48781,threat-actor,188,194,48782,threat-actor,210,217,48783.0,threat-actor,220.0,229.0
3,13600,(Note that Flash has been declared end-of-life...,"[{'from_id': 51688, 'id': 1133, 'to_id': 51689...",The diagnosis is a malware infection. The enti...,1. Implementing a robust antivirus software th...,51687,TIME,62,79,51688,malware,207,215,51689.0,malware,247.0,258.0
4,14364,Figure 21. Connection of Maikspy variants to 1...,"[{'from_id': 51780, 'id': 1161, 'to_id': 44372...",The diagnosis is that Maikspy malware variants...,1. Implementing a robust firewall system that ...,51779,URL,163,191,51777,URL,70,93,51781.0,malware,120.0,127.0
5,13565,The source code of this framework is shared ac...,"[{'from_id': 51647, 'id': 1123, 'to_id': 51646...",Possible diagnosis: Data Leakage Explanation:...,1. Implement access controls: Restrict access ...,51646,location,56,63,51647,tools,24,33,NaN,NaN,NaN,NaN
6,2400,The CVE-2022-22965 vulnerability allows an att...,"[{'from_id': 45496, 'id': 105, 'to_id': 45495,...",The entity identified by ID 45495 is vulnerabl...,1. Patch the vulnerability: The most straightf...,45495,vulnerability,4,18,45496,attack-pattern,52,89,45497.0,identity,103.0,110.0
7,14126,"At the same time, we were able to locate the M...","[{'from_id': 48191, 'id': 392, 'to_id': 48192,...",The cybersecurity issue is not specified in th...,Without a specific cybersecurity issue to addr...,48192,location,73,79,48191,Infrastucture,127,144,48193.0,Infrastucture,45.0,62.0
8,1929,But this link is further fortified by the Andr...,"[{'from_id': 45182, 'id': 80, 'to_id': 45183, ...",The diagnosis is that Patchwork threat actor g...,1. Implementing strong network security measur...,45181,SOFTWARE,42,49,45183,threat-actor,169,178,45184.0,threat-actor,233.0,242.0
9,1921,A malicious RTF file that exploits the CVE-20...,"[{'from_id': 47045, 'id': 291, 'to_id': 47039,...",The diagnosis is a malware infection resulting...,1. Patching the vulnerabilities: The first and...,47039,vulnerability,40,53,47042,url,247,262,47043.0,identity,264.0,269.0

In [10]:
display(df.sample(min(10, len(df)), random_state=42))
print("\n--- Dtypes ---")
print(df.dtypes)
print("\n--- Info ---")
df.info()

,id,text,relations,diagnosis,solutions,id_1,label_1,start_offset_1,end_offset_1,id_2,label_2,start_offset_2,end_offset_2,id_3,label_3,start_offset_3,end_offset_3
467,13552,"Taken together, this led us to believe that Wa...","[{'from_id': 51628, 'id': 1118, 'to_id': 42261...",Water Pamola is conducting a campaign that inv...,1. Implement regular vulnerability scanning an...,51628,campaign,44,56,42261,attack-pattern,90,93,NaN,NaN,NaN,NaN
33,3719,"In both Carbanak and FIN7 attacks, communicati...","[{'from_id': 49518, 'id': 817, 'to_id': 49519,...",The entities of the diagnosis are two threat a...,1. Implement advanced firewalls and intrusion ...,49518,threat-actor,8,16,49519,threat-actor,21,25,49520.0,attack-pattern,97.0,116.0
131,3361,Python.BIOPASS.A ee4150f18ed826c032e7407468be...,"[{'from_id': 10175, 'id': 532, 'to_id': 48977,...",The entity with ID 48977 is diagnosed with the...,1. Implementing antivirus software that is cap...,10175,hash,18,82,48977,malware,0,16,NaN,NaN,NaN,NaN
72,354,TrustedSec reports on how attackers were appar...,"[{'from_id': 44714, 'id': 18, 'to_id': 44712, ...",The diagnosis is a successful exploitation of ...,1. Patching the Heartbleed vulnerability: This...,44711,identity,0,10,44712,vulnerability,113,137,44713.0,tools,167.0,170.0
78,876,analysis sample PClock2 is written in Visual ...,"[{'from_id': 44898, 'id': 188, 'to_id': 46410,...",The diagnosis is that the entity identified as...,1. Install and regularly update antivirus soft...,46410,SOFTWARE,39,51,44898,malware,17,24,NaN,NaN,NaN,NaN
113,3768,Our research so far has shown one publicly kno...,"[{'from_id': 49601, 'id': 841, 'to_id': 49600,...",The entity /usr/local/horizon/scripts/publishC...,1. Patching: Install the latest security patch...,49600,vulnerability,87,101,49601,FILEPATH,121,165,NaN,NaN,NaN,NaN
274,2594,"In December 2021, the Ministry of Health of Br...","[{'from_id': 47780, 'id': 351, 'to_id': 47779,...",Cybersecurity issue: Attack Entity: Ministry o...,1. Implementing multi-factor authentication fo...,47778,TIME,3,16,47780,threat-actor,87,94,47779.0,identity,22.0,50.0
185,3340,It is well known that the Winnti Group has pre...,"[{'from_id': 48949, 'id': 507, 'to_id': 48950,...","The Winnti Group, a known threat actor, is usi...",1. Regularly monitor and update digital certif...,48950,attack-pattern,59,78,48949,threat-actor,26,38,NaN,NaN,NaN,NaN
261,947,Taomike is a Chinese company that aims to beco...,"[{'from_id': 46455, 'id': 192, 'to_id': 46456,...",Possible diagnosis: Taomike may be vulnerable ...,1. Implement strong authentication and access ...,46455,identity,1,8,46456,location,14,21,46457.0,location,104.0,109.0
9,1921,A malicious RTF file that exploits the CVE-20...,"[{'from_id': 47045, 'id': 291, 'to_id': 47039,...",The diagnosis is a malware infection resulting...,1. Patching the vulnerabilities: The first and...,47039,vulnerability,40,53,47042,url,247,262,47043.0,identity,264.0,269.0

--- Dtypes ---
id                  int64
text               object
relations          object
diagnosis          object
solutions          object
id_1                int64
label_1            object
start_offset_1      int64
end_offset_1        int64
id_2                int64
label_2            object
start_offset_2      int64
end_offset_2        int64
id_3              float64
label_3            object
start_offset_3    float64
end_offset_3      float64
dtype: object

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 476 entries, 0 to 475
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              476 non-null    int64
 1   text            476 non-null    object
 2   relations       476 non-null    object
 3   diagnosis       475 non-null    object
 4   solutions       476 non-null    object
 5   id_1            476 non-null    int64
 6   label_1         476 non-null    object
 7   start_offset_1  476 non-null    int64
 8   end_offset_1    476 non-null    int64
 9   id_2            476 non-null    int64
 10  label_2         476 non-null    object
 11  start_offset_2  476 non-null    int64
 12  end_offset_2    476 non-null    int64
 13  id_3            329 non-null    float64
 14  label_3         329 non-null    object
 15  start_offset_3  329 non-null    float64
 16  end_offset_3    329 non-null    float64
dtypes: float64(3), int64(7), object(7)
memory usage: 63.3+ KB

In [11]:
df.describe(include=['object', 'int'])

,id,text,relations,diagnosis,solutions,id_1,label_1,start_offset_1,end_offset_1,id_2,label_2,start_offset_2,end_offset_2,label_3
count,476.000000,476,476,475,476,476.000000,476,476.000000,476.000000,476.000000,476,476.000000,476.000000,329
unique,NaN,391,404,430,432,NaN,17,NaN,NaN,NaN,17,NaN,NaN,17
top,NaN,Follina is a remote code execution (RCE) vulne...,"[{'from_id': 10265, 'id': 640, 'to_id': 49066,...",Diagnosis: WatchGuard Firebox devices have bee...,1. Implementing a comprehensive threat intelli...,NaN,malware,NaN,NaN,NaN,malware,NaN,NaN,malware
freq,NaN,3,2,2,2,NaN,141,NaN,NaN,NaN,90,NaN,NaN,68
mean,4672.651261,NaN,NaN,NaN,NaN,41037.617647,NaN,63.703782,77.376050,43544.147059,NaN,81.987395,98.976891,NaN
std,4178.163473,NaN,NaN,NaN,NaN,16171.093234,NaN,62.684830,64.789955,13357.982594,NaN,68.756656,71.263909,NaN
min,105.000000,NaN,NaN,NaN,NaN,377.000000,NaN,0.000000,4.000000,771.000000,NaN,0.000000,4.000000,NaN
25%,2023.500000,NaN,NaN,NaN,NaN,45168.250000,NaN,16.000000,28.000000,45615.500000,NaN,34.000000,49.000000,NaN
50%,3442.500000,NaN,NaN,NaN,NaN,48220.500000,NaN,46.000000,58.500000,48311.000000,NaN,65.000000,88.500000,NaN
75%,4821.000000,NaN,NaN,NaN,NaN,50081.000000,NaN,93.250000,110.000000,50062.250000,NaN,117.000000,134.000000,NaN
max,14408.000000,NaN,NaN,NaN,NaN,51779.000000,NaN,428.000000,451.000000,51777.000000,NaN,471.000000,535.000000,NaN

In [12]:
#valeur n/a
df.isna().sum()

id                  0
text                0
relations           0
diagnosis           1
solutions           0
id_1                0
label_1             0
start_offset_1      0
end_offset_1        0
id_2                0
label_2             0
start_offset_2      0
end_offset_2        0
id_3              147
label_3           147
start_offset_3    147
end_offset_3      147
dtype: int64

## **MEANING OF EVERY COLUMN**
id :
Unique identifier for each record (one row = one case/communication instance).

text : 
Raw textual content carried over the network (e.g., email/message body or payload). It may contain mentions of threats, actors, or attack patterns.

Entries (list of JSON objects) : 
Detected entities (and their spans) within text. Each object includes:

sender_id: ID of the entity that initiated/sent the communication.

label: Entity/threat type (e.g., malware, attack pattern, identity, benign, software attack, threat actor).

start_offset: Start character index of the entity mention in text.

end_offset: End character index of the entity mention in text.

receiver_ids: List of IDs for entities that received or were targeted.

relations (list of tuples)
Pairs of entity IDs describing directed relationships (source ID → target ID) between entities mentioned in Entries (e.g., “threat actor uses malware”, “malware targets identity”).

diagnosis
Human- or system-generated description/assessment of the identified cyber threat in this instance (what it is, impact, context).

solution
Recommended mitigations or actions to address the diagnosed threat (e.g., patches, controls, configurations, updates).

## **Transformation :**

In [13]:
df.head(10)

,id,text,relations,diagnosis,solutions,id_1,label_1,start_offset_1,end_offset_1,id_2,label_2,start_offset_2,end_offset_2,id_3,label_3,start_offset_3,end_offset_3
0,249,A cybersquatting domain save-russia[.]today is...,"[{'from_id': 44658, 'id': 9, 'to_id': 44659, '...",The diagnosis is a cyber attack that involves ...,1. Implementing DNS filtering to block access ...,44656,attack-pattern,2,16,44657,url,24,43,44658.0,attack-pattern,57.0,68.0
1,14309,"Like the Android Maikspy, it first sends a not...","[{'from_id': 48531, 'id': 445, 'to_id': 48532,...",The diagnosis is that the entity identified as...,1. Implementing a robust anti-malware software...,48530,SOFTWARE,9,17,48531,malware,17,24,48532.0,Infrastucture,63.0,73.0
2,13996,While analyzing the technical details of this ...,"[{'from_id': 48781, 'id': 461, 'to_id': 48782,...",Diagnosis: APT37/Reaper/Group 123 is responsib...,1. Implementing advanced threat detection tech...,48781,threat-actor,188,194,48782,threat-actor,210,217,48783.0,threat-actor,220.0,229.0
3,13600,(Note that Flash has been declared end-of-life...,"[{'from_id': 51688, 'id': 1133, 'to_id': 51689...",The diagnosis is a malware infection. The enti...,1. Implementing a robust antivirus software th...,51687,TIME,62,79,51688,malware,207,215,51689.0,malware,247.0,258.0
4,14364,Figure 21. Connection of Maikspy variants to 1...,"[{'from_id': 51780, 'id': 1161, 'to_id': 44372...",The diagnosis is that Maikspy malware variants...,1. Implementing a robust firewall system that ...,51779,URL,163,191,51777,URL,70,93,51781.0,malware,120.0,127.0
5,13565,The source code of this framework is shared ac...,"[{'from_id': 51647, 'id': 1123, 'to_id': 51646...",Possible diagnosis: Data Leakage Explanation:...,1. Implement access controls: Restrict access ...,51646,location,56,63,51647,tools,24,33,NaN,NaN,NaN,NaN
6,2400,The CVE-2022-22965 vulnerability allows an att...,"[{'from_id': 45496, 'id': 105, 'to_id': 45495,...",The entity identified by ID 45495 is vulnerabl...,1. Patch the vulnerability: The most straightf...,45495,vulnerability,4,18,45496,attack-pattern,52,89,45497.0,identity,103.0,110.0
7,14126,"At the same time, we were able to locate the M...","[{'from_id': 48191, 'id': 392, 'to_id': 48192,...",The cybersecurity issue is not specified in th...,Without a specific cybersecurity issue to addr...,48192,location,73,79,48191,Infrastucture,127,144,48193.0,Infrastucture,45.0,62.0
8,1929,But this link is further fortified by the Andr...,"[{'from_id': 45182, 'id': 80, 'to_id': 45183, ...",The diagnosis is that Patchwork threat actor g...,1. Implementing strong network security measur...,45181,SOFTWARE,42,49,45183,threat-actor,169,178,45184.0,threat-actor,233.0,242.0
9,1921,A malicious RTF file that exploits the CVE-20...,"[{'from_id': 47045, 'id': 291, 'to_id': 47039,...",The diagnosis is a malware infection resulting...,1. Patching the vulnerabilities: The first and...,47039,vulnerability,40,53,47042,url,247,262,47043.0,identity,264.0,269.0

Concernant la transformation, l'idée serait de pouvoir donné un score en fonction de chaque label qu'il y a. C'est a dire, de notre coté donné un niveau de criticité correspondant à chaque label. Par exemple Threat-actor pourrait valoir 5 en criticité comme étant le max, alors que URL pourrait être 1 étant le plus faible. Puis, on pourrait aussi prédire les solutions possible en fonction du type d'attaque.

### **PRETRAITEMENT**

Suppression des colonnes inutiles, cleaning the text

In [15]:
cols_to_keep = [
    "id",
    "text",
    "diagnosis",
    "solutions",
    "label_1",
    "label_2",
    "label_3",
]

df = df[cols_to_keep]
df.head(10)

,id,text,diagnosis,solutions,label_1,label_2,label_3
0,249,A cybersquatting domain save-russia[.]today is...,The diagnosis is a cyber attack that involves ...,1. Implementing DNS filtering to block access ...,attack-pattern,url,attack-pattern
1,14309,"Like the Android Maikspy, it first sends a not...",The diagnosis is that the entity identified as...,1. Implementing a robust anti-malware software...,SOFTWARE,malware,Infrastucture
2,13996,While analyzing the technical details of this ...,Diagnosis: APT37/Reaper/Group 123 is responsib...,1. Implementing advanced threat detection tech...,threat-actor,threat-actor,threat-actor
3,13600,(Note that Flash has been declared end-of-life...,The diagnosis is a malware infection. The enti...,1. Implementing a robust antivirus software th...,TIME,malware,malware
4,14364,Figure 21. Connection of Maikspy variants to 1...,The diagnosis is that Maikspy malware variants...,1. Implementing a robust firewall system that ...,URL,URL,malware
5,13565,The source code of this framework is shared ac...,Possible diagnosis: Data Leakage Explanation:...,1. Implement access controls: Restrict access ...,location,tools,NaN
6,2400,The CVE-2022-22965 vulnerability allows an att...,The entity identified by ID 45495 is vulnerabl...,1. Patch the vulnerability: The most straightf...,vulnerability,attack-pattern,identity
7,14126,"At the same time, we were able to locate the M...",The cybersecurity issue is not specified in th...,Without a specific cybersecurity issue to addr...,location,Infrastucture,Infrastucture
8,1929,But this link is further fortified by the Andr...,The diagnosis is that Patchwork threat actor g...,1. Implementing strong network security measur...,SOFTWARE,threat-actor,threat-actor
9,1921,A malicious RTF file that exploits the CVE-20...,The diagnosis is a malware infection resulting...,1. Patching the vulnerabilities: The first and...,vulnerability,url,identity

In [18]:
# 3. Définir les colonnes textuelles à nettoyer
text_cols = ["text", "diagnosis", "solutions"]

def clean_text(s):
    """Nettoyage simple d'un texte."""
    if pd.isna(s):
        return s
    # a) tout en minuscules
    s = s.lower()
    # b) enlever les retours à la ligne
    s = s.replace("\n", " ").replace("\r", " ")
    # c) supprimer les espaces multiples
    s = ' '.join(s.split())
    # d) enlever les espaces au début / à la fin
    s = s.strip()
    return s

for col in text_cols:
    df[col] = df[col].apply(clean_text)

In [19]:
# 4. Supprimer les lignes inutilisables
# - lignes sans texte
# - (optionnel) lignes sans label_1 si tu choisis label_1 comme cible
df = df.dropna(subset=["text"])       # on veut au moins un texte
df = df.dropna(subset=["label_1"])    # cible non nulle pour entraîner un modèle

In [23]:
# 5. Supprimer les doublons éventuels texte + label_1
df = df.drop_duplicates(subset=["text", "label_1"])

print("Shape après nettoyage :", df.shape)

Shape après nettoyage : (398, 7)

In [24]:
# 6. (Optionnel) sauvegarder le dataset pré-traité
df.to_csv("cyber_dataset_clean.csv", index=False)

In [25]:
df.head(10)

,id,text,diagnosis,solutions,label_1,label_2,label_3
0,249,a cybersquatting domain save-russia[.]today is...,the diagnosis is a cyber attack that involves ...,1. implementing dns filtering to block access ...,attack-pattern,url,attack-pattern
1,14309,"like the android maikspy, it first sends a not...",the diagnosis is that the entity identified as...,1. implementing a robust anti-malware software...,SOFTWARE,malware,Infrastucture
2,13996,while analyzing the technical details of this ...,diagnosis: apt37/reaper/group 123 is responsib...,1. implementing advanced threat detection tech...,threat-actor,threat-actor,threat-actor
3,13600,(note that flash has been declared end-of-life...,the diagnosis is a malware infection. the enti...,1. implementing a robust antivirus software th...,TIME,malware,malware
4,14364,figure 21. connection of maikspy variants to 1...,the diagnosis is that maikspy malware variants...,1. implementing a robust firewall system that ...,URL,URL,malware
5,13565,the source code of this framework is shared ac...,possible diagnosis: data leakage explanation: ...,1. implement access controls: restrict access ...,location,tools,NaN
6,2400,the cve-2022-22965 vulnerability allows an att...,the entity identified by id 45495 is vulnerabl...,1. patch the vulnerability: the most straightf...,vulnerability,attack-pattern,identity
7,14126,"at the same time, we were able to locate the m...",the cybersecurity issue is not specified in th...,without a specific cybersecurity issue to addr...,location,Infrastucture,Infrastucture
8,1929,but this link is further fortified by the andr...,the diagnosis is that patchwork threat actor g...,1. implementing strong network security measur...,SOFTWARE,threat-actor,threat-actor
9,1921,a malicious rtf file that exploits the cve-201...,the diagnosis is a malware infection resulting...,1. patching the vulnerabilities: the first and...,vulnerability,url,identity

## **PROBLEMATIQUE :**
Ce qu'on pourrait faire c'est de pouvoir évaluer la criticité d'un probleme à partir d'un texte.
On pourrait aussi prédire les solutions possible en fonction du type d'attaque